# Use https (public access) instead of git for git-submodules. This modifies only Travis-CI behavior!
# using greentealatte as testing framework and kept as a submodule
# permission is denied when trying to clone a submodule with ssh, changing to https as it is a public repo
# disable the default submodule logic
git:
  submodules: false
# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

# testing with different java versions
language: java
jdk:
  - oraclejdk8
# greentealatte uses lambda expression and will not work on anything less than jdk8
#  - oraclejdk7
#  - openjdk6

# add all test files
script:
  - javac test/AllTests.java
  - java test.AllTests
